### ISSUE TITLE
Play Against Computer (Feature)

### ISSUE THREAD

**Issue by DylanCDR** [DylanCDR/OpenSourceAssignment#3]
Add a feature to have a computer play against the user.

**Comment by carinazchan** [comment]
The owner did not give write permissions to this open source repo so I forked it: [https://github.com/carinazchan/OpenSourceAssignment.git](url)

Play Against Computer (Feature)
- Only contributed to tic_tac_toe.py
- Functions added: is_computer_player(), get_computer_move(), _start_two_player_game(), _start_cpu_player_game()
- User is prompted in terminal for game mode

**Comment by carinazchan** [comment]
I have merged my commit with the main branch.
All tests passed (unit tests and linter).
